include:
  - local: '.gitlab/ci/**/.gitlab-ci.yml'

stages:
  - lint
  - test

tests:
  stage: test
  needs: []
  image: python:3.13-slim@sha256:51e1a0a317fdb6e170dc791bbeae63fac5272c82f43958ef74a34e170c6f8b18
  services:
    - docker:29.1.5-dind@sha256:3a33fc81fa4d38360f490f5b900e9846f725db45bb1d9b1fe02d849bd42a5cf2
  variables:
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    GIT_DEPTH: "0"  # All git tags needed for copier
    # When using dind service, you must instruct Docker to talk with
    # the daemon started inside of the service
    # These are usually specified by the entrypoint, if using the "docker" image
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"  # should be mounded by the gitlab runner
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - apt-get update && apt-get install -y git curl
    - apt-get install --no-install-recommends -y docker-cli
    - curl -LsSf https://astral.sh/uv/0.9.26/install.sh | sh
    - source $HOME/.local/bin/env
    - ./scripts/install-task.sh -b /usr/local/bin
    - task dev-setup:venv
  script:
    - task test
  cache:
    - key: tests-uv
      paths:
        - ${UV_CACHE_DIR}
    - key: tests-pre-commit
      paths:
        - ${PRE_COMMIT_HOME}
