include:
  - local: '.gitlab/ci/**/.gitlab-ci.yml'

stages:
  - lint
  - test

tests:
  stage: test
  needs: []
  image: python:3.13-slim@sha256:05b118ecc93ea09e30569706568fb251c71b77d2a3908d338b77be033e162b59
  services:
    - docker:29.0.2-dind@sha256:d003717ad7a27d359dd2f5f6aa6ca691f5f58671e8d1ff0277d07e5635bb8332
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    GIT_DEPTH: "0"  # All git tags needed for copier
    # When using dind service, you must instruct Docker to talk with
    # the daemon started inside of the service
    # These are usually specified by the entrypoint, if using the "docker" image
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"  # should be mounded by the gitlab runner
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - apt-get update && apt-get install -y git curl
    - apt-get install --no-install-recommends -y docker-cli
    - python -m venv venv
    - source venv/bin/activate
    - ./scripts/install-task.sh -b /usr/local/bin
    - task dev-setup:virtualenv
  script:
    - task test
  cache:
    - key: tests-pip
      paths:
        - ${PIP_CACHE_DIR}
    - key: tests-pre-commit
      paths:
        - ${PRE_COMMIT_HOME}
