include:
  - local: '.gitlab/ci/**/.gitlab-ci.yml'

stages:
  - lint
  - test

tests:
  stage: test
  needs: []
  image: python:3.12-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    GIT_DEPTH: "0"
  before_script:
    - apt-get update && apt-get install -y git curl
    - python -m venv venv
    - source venv/bin/activate
    - ./scripts/install-task.sh -b /usr/local/bin
    - task dev-setup:virtualenv
  script:
    - python -m pytest
  cache:
    - key: tests-pip
      paths:
        - ${PIP_CACHE_DIR}
    - key: tests-pre-commit
      paths:
        - ${PRE_COMMIT_HOME}
