[project]
name = "copier-template-copier-template"
version = "0.0.0"
description = "Copier template for copier-template"
readme = "README.md"
dependencies = [
    "copier>=9.6.0",
    "copier-templates-extensions>=0.3.2",
]
requires-python = ">= 3.13"

[dependency-groups]
dev = [
    "plumbum>=1.10.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-gitconfig>=0.9.0",
    "pyyaml>=6.0.3",
]

[tool.pytest]
minversion = "9.0"
testpaths = [
    "tests",
]
addopts = [
    "--ignore=tmp",
    "--ignore=parent_template",
]
norecursedirs = ["tmp*", "parent_template"]
