---
tests:
  stage: test
  needs: []
  image: debian:trixie-slim@sha256:4ffb3a1511099754cddc70eb1b12e50ffdb67619aa0ab6c13fcd800a78ef7c7a
  services:
    - name: docker:dind@sha256:edaa00c1ab17574f96a93508de97c699dee40a9593b69e6bb0c2b8810d73c505
      command: ["--registry-mirror", "http://host.docker.internal:5000"]
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.13", "3.14"]
  variables:
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
    PREK_HOME: "$CI_PROJECT_DIR/.cache/prek"
    UV_PYTHON: "$PYTHON_VERSION"
    GIT_DEPTH: "0"  # All git tags needed for copier
    # When using dind service, you must instruct Docker to talk with
    # the daemon started inside of the service
    # These are usually specified by the entrypoint, if using the "docker" image
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"  # should be mounded by the gitlab runner
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - apt-get update && apt-get install -y git curl
    - apt-get install --no-install-recommends -y docker-cli
    - curl -LsSf https://astral.sh/uv/0.11.7/install.sh | sh
    - source $HOME/.local/bin/env
    - uv python install $PYTHON_VERSION
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin v3.50.0
    - task dev-setup:venv
  script:
    - task test
  cache:
    - key: tests-uv-py$PYTHON_VERSION
      paths:
        - ${UV_CACHE_DIR}
    - key: tests-prek-py$PYTHON_VERSION
      paths:
        - ${PREK_HOME}
