---
tests:
  stage: test
  needs: []
  image: debian:trixie-slim@sha256:26f98ccd92fd0a44d6928ce8ff8f4921b4d2f535bfa07555ee5d18f61429cf0c
  services:
    - name: docker:29.3.1-dind@sha256:4d90f1f6c400315c2dba96d3ec93c01e64198395cbba04f79d12adce4f737029
      command: ["--registry-mirror", "http://host.docker.internal:5000"]
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.13", "3.14"]
  variables:
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
    PREK_HOME: "$CI_PROJECT_DIR/.cache/prek"
    UV_PYTHON: "$PYTHON_VERSION"
    GIT_DEPTH: "0"  # All git tags needed for copier
    # When using dind service, you must instruct Docker to talk with
    # the daemon started inside of the service
    # These are usually specified by the entrypoint, if using the "docker" image
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"  # should be mounded by the gitlab runner
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - apt-get update && apt-get install -y git curl
    - apt-get install --no-install-recommends -y docker-cli
    - docker info
    - curl -LsSf https://astral.sh/uv/0.11.3/install.sh | sh
    - source $HOME/.local/bin/env
    - uv python install $PYTHON_VERSION
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin v3.49.1
    - task dev-setup:venv
  script:
    - task test
  cache:
    - key: tests-uv-py$PYTHON_VERSION
      paths:
        - ${UV_CACHE_DIR}
    - key: tests-prek-py$PYTHON_VERSION
      paths:
        - ${PREK_HOME}
