version: '3'

set: [pipefail]

tasks:
  default:
    cmds:
      - task --list

  dev-setup:
    desc: Bootstrap dev setup
    cmds:
      - pre-commit install
      - task: dev-setup:virtualenv

  dev-setup:virtualenv-base:
    desc: Install dev requirements
    requires:
      vars: [VIRTUAL_ENV]
    preconditions:
      - sh: '[ "{{.VIRTUAL_ENV | base }}" != "global" ]'
        msg: "Must be in a virtualenv not called global"
    cmds:
      - pip install --upgrade pip pip-tools

  dev-setup:virtualenv:
    desc: Install dev requirements
    cmds:
      - task: dev-setup:virtualenv-base
      - pip-sync requirements-dev.txt

  maintenance:
    desc: Project maintenance automation
    cmds:
      - pre-commit autoupdate
      - task: maintenance:requirements-dev

  maintenance:requirements-dev:
    vars:
      FLAGS: '{{.FLAGS | default "--rebuild --upgrade" }}'
    cmds:
      - task: dev-setup:virtualenv-base
      - pip-compile {{.FLAGS}} requirements-dev.in

  test:
    desc: Run tests
    cmds:
      - rm -rf ./tmp/tests
      - mkdir -p ./tmp/
      - pytest --basetemp=./tmp/tests/ -s {{.CLI_ARGS}}

  diff:
    desc: Compare last version to HEAD
    cmds:
      - rm -rf tmp/before
      - rm -rf tmp/after
      - copier copy . tmp/before
      - copier copy --vcs-ref HEAD . tmp/after
      - diff tmp/before tmp/after

  example:docker-mount:
    desc: "Example using docker with volumes to test in CI"
    cmds:
      - docker info
      - docker run -v $(pwd):/code/ --entrypoint=/bin/bash python:3.12-slim -c 'cat /code/semantic_release.toml'
