pre-commit:
  stage: lint
  needs: []
  image: python:3.14-slim@sha256:1a3c6dbfd2173971abba880c3cc2ec4643690901f6ad6742d0827bae6cefc925
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  before_script:
    - apt-get update && apt-get install -y git
    - pip install pre-commit
  script:
    - pre-commit install --install-hooks
    - pre-commit run --all-files
  cache:
    - key: pip
      paths:
        - ${PIP_CACHE_DIR}
    - key: pre-commit
      paths:
        - ${PRE_COMMIT_HOME}
