pre-commit:
  stage: lint
  needs: []
  image: python:3.14-slim@sha256:5e59aae31ff0e87511226be8e2b94d78c58f05216efda3b07dbbed938ec8583b
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PREK_HOME: "$CI_PROJECT_DIR/.cache/prek"
  before_script:
    - apt-get update && apt-get install -y git
    - pip install prek
  script:
    - prek run --all-files
  cache:
    - key: pip
      paths:
        - ${PIP_CACHE_DIR}
    - key: prek
      paths:
        - ${PREK_HOME}
