pre-commit:
  stage: lint
  needs: []
  image: python:3.13-slim@sha256:a93b51c5acbd72f9d28fd811a230c67ed59bcd727ac08774dee4bbf64b7630c7
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  before_script:
    - apt-get update && apt-get install -y git
    - pip install pre-commit
  script:
    - pre-commit install --install-hooks
    - pre-commit run --all-files
  cache:
    - key: pip
      paths:
        - ${PIP_CACHE_DIR}
    - key: pre-commit
      paths:
        - ${PRE_COMMIT_HOME}
